db:
  user: "root"
  pass: "root"
  host: "db"
  port: "3306"
  database: "timeclub"

service:
  name: "club-service"
  port: 8080
  host: "club-service"

consul:
  enabled: true
  port: 8500
  check:
    interval: '5s'
    timeout: '3s'