version: '3.7'

services:
  consul-server:
    image: consul:1.10
    container_name: consul-server
    restart: always
    networks:
      - net
    ports:
      - '8500:8500'
      - '8600:8600/tcp'
      - '8600:8600/udp'
    environment:
      CONSUL_LOCAL_CONFIG: |
        {
          "log_level": "info"
        }


  app-db:
    image: mysql:5.7.16
    container_name: app-db
    restart: always
    networks:
      - net
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'timeclub'
    volumes:
      - mysql1:/var/lib/mysql

  club-service:
    image: golang:1.17
    container_name: club-service
    working_dir: /app
    volumes:
      - ./:/app
      - go-modules:/go
    command: bash -c "cd club_service && go mod download && go run ./main.go"
    environment:
      VIPER_CONFIG_NAME: 'docker'
      DB_HOST: 'app-db'
      SERVICE_HOST: 'club-service'
      CONSUL_HOST: 'consul-server'
      CONSUL_CHECK_INTERVAL: '60s'
      SERVICE_PORT: 8881
    ports:
      - '8881:8881'
    depends_on:
      - consul-server
      - app-db
    networks:
      - net

  club-service1:
    image: golang:1.17
    container_name: club-service1
    working_dir: /app
    volumes:
      - ./:/app
      - go-modules:/go
    command: bash -c "cd club_service && go mod download && go run ./main.go"
    environment:
      VIPER_CONFIG_NAME: 'docker'
      DB_HOST: 'app-db'
      SERVICE_HOST: 'club-service1'
      CONSUL_HOST: 'consul-server'
      CONSUL_CHECK_INTERVAL: '60s'
      SERVICE_PORT: 8883
    ports:
      - '8883:8883'
    depends_on:
      - consul-server
      - app-db
    networks:
      - net

  visit-service:
    image: golang:1.17
    container_name: visit-service
    working_dir: /app
    volumes:
      - ./:/app
      - go-modules:/go
    command: bash -c "cd visit_service && go mod download && go run ./main.go"
    environment:
      VIPER_CONFIG_NAME: 'docker'
      DB_HOST: 'app-db'
      SERVER_HOST: 'visit-service'
      CONSUL_HOST: 'consul-server'
      CONSUL_CHECK_INTERVAL: '60s'
      SERVER_PORT_HTTP: 8882
    ports:
      - '8882:8882'
    depends_on:
      - consul-server
      - app-db
    networks:
      - net

  client-service:
    image: golang:1.17
    container_name: client-service
    working_dir: /app
    volumes:
      - ./:/app
      - go-modules:/go
    command: bash -c "cd client_service && go mod download && go run ./main.go"
    environment:
      VIPER_CONFIG_NAME: 'docker'
      DB_HOST: 'app-db'
      SERVER_HOST: 'client-service'
      CONSUL_HOST: 'consul-server'
      SERVER_PORT_HTTP: 8884
    ports:
      - '8884:8884'
    depends_on:
      - consul-server
      - app-db
    networks:
      - net

  card-service:
    image: golang:1.17
    container_name: card-service
    working_dir: /app
    volumes:
      - ./:/app
      - go-modules:/go
    command: bash -c "cd card_service && go mod download && go run ./main.go"
    environment:
      VIPER_CONFIG_NAME: 'docker'
      DB_HOST: 'app-db'
      SERVER_HOST: 'card-service'
      CONSUL_HOST: 'consul-server'
      SERVER_PORT_HTTP: 8885
    ports:
      - '8885:8885'
    depends_on:
      - consul-server
      - app-db
    networks:
      - net

  api-gateway:
    image: golang:1.17
    container_name: api-gateway
    working_dir: /app
    volumes:
      - ./:/app
      - go-modules:/go
    command: bash -c "cd api_gateway && go mod download && go run ./main.go"
    environment:
      VIPER_CONFIG_NAME: 'docker'
      SERVER_HOST: 'api-gateway'
      CONSUL_HOST: 'consul-server'
      SERVER_PORT_HTTP: 80
    ports:
      - '80:80'
    depends_on:
      - consul-server
    networks:
      - net

volumes:
  mysql1:
    driver: local
  go-modules:
    driver: local

networks:
  net:
    driver: bridge