// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

// Create provides a mock function with given fields: visits
func (_m *OrderService) Create(visits []int64) (interface{}, error) {
	ret := _m.Called(visits)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func([]int64) interface{}); ok {
		r0 = rf(visits)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]int64) error); ok {
		r1 = rf(visits)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
