service:
  name: "visit-service"

server:
  port:
    http: 8081
    grpc: 9081
  host: localhost

db:
  user: "root"
  pass: "root"
  host: "db"
  port: "3306"
  database: "timeclub"

client:
  club:
    grpc:
      url: "localhost:9080"

consul:
  enabled: true
  port: 8500
  check:
    interval: '5s'
    timeout: '3s'