// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	api "github.com/andrewd92/timeclub/club_service/api"

	mock "github.com/stretchr/testify/mock"
)

// ClubClient is an autogenerated mock type for the ClubClient type
type ClubClient struct {
	mock.Mock
}

// GetById provides a mock function with given fields: id
func (_m *ClubClient) GetById(id int64) (*api.Club, error) {
	ret := _m.Called(id)

	var r0 *api.Club
	if rf, ok := ret.Get(0).(func(int64) *api.Club); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Club)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
