db:
  user: "root"
  pass: "root"
  host: "localhost"
  port: "3306"
  database: "timeclub"

service:
  name: "card-service"

server:
  port:
    http: 8082
    grpc: 9080
  host: localhost

consul:
  enabled: false