// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	price_list "github.com/andrewd92/timeclub/club_service/domain/price_list"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetById provides a mock function with given fields: id
func (_m *Repository) GetById(id int64) (*price_list.PriceList, error) {
	ret := _m.Called(id)

	var r0 *price_list.PriceList
	if rf, ok := ret.Get(0).(func(int64) *price_list.PriceList); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*price_list.PriceList)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
