// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	club "github.com/andrewd92/timeclub/club_service/domain/club"
	club_dao "github.com/andrewd92/timeclub/club_service/infrastructure/dao/club_dao"
	mock "github.com/stretchr/testify/mock"
)

// ClubDao is an autogenerated mock type for the ClubDao type
type ClubDao struct {
	mock.Mock
}

// GetAll provides a mock function with given fields:
func (_m *ClubDao) GetAll() ([]*club_dao.ClubModel, error) {
	ret := _m.Called()

	var r0 []*club_dao.ClubModel
	if rf, ok := ret.Get(0).(func() []*club_dao.ClubModel); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*club_dao.ClubModel)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: id
func (_m *ClubDao) GetById(id int64) (*club_dao.ClubModel, error) {
	ret := _m.Called(id)

	var r0 *club_dao.ClubModel
	if rf, ok := ret.Get(0).(func(int64) *club_dao.ClubModel); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*club_dao.ClubModel)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: _a0
func (_m *ClubDao) Insert(_a0 *club.Club) (int64, error) {
	ret := _m.Called(_a0)

	var r0 int64
	if rf, ok := ret.Get(0).(func(*club.Club) int64); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*club.Club) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
