service:
  name: "visit-service"

server:
  port:
    http: 8085
    grpc: 9085
  host: localhost

db:
  user: "root"
  pass: "root"
  host: "localhost"
  port: "3306"
  database: "timeclub"

client:
  club:
    grpc:
      url: "localhost:9080"

consul:
  enabled: false