// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	visit "github.com/andrewd92/timeclub/visit_service/domain/visit"
	mock "github.com/stretchr/testify/mock"
)

// Factory is an autogenerated mock type for the Factory type
type Factory struct {
	mock.Mock
}

// Create provides a mock function with given fields: clubId, cardId
func (_m *Factory) Create(clubId int64, cardId int64) *visit.Visit {
	ret := _m.Called(clubId, cardId)

	var r0 *visit.Visit
	if rf, ok := ret.Get(0).(func(int64, int64) *visit.Visit); ok {
		r0 = rf(clubId, cardId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*visit.Visit)
		}
	}

	return r0
}
