// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	visit "github.com/andrewd92/timeclub/visit_service/domain/visit"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetAll provides a mock function with given fields:
func (_m *Repository) GetAll() ([]*visit.Visit, error) {
	ret := _m.Called()

	var r0 []*visit.Visit
	if rf, ok := ret.Get(0).(func() []*visit.Visit); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*visit.Visit)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: _a0
func (_m *Repository) Save(_a0 *visit.Visit) (*visit.Visit, error) {
	ret := _m.Called(_a0)

	var r0 *visit.Visit
	if rf, ok := ret.Get(0).(func(*visit.Visit) *visit.Visit); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*visit.Visit)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*visit.Visit) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
